#!/usr/bin/python3
"""Basic control of the robot, move forward and avoid obstacles. Doesn't get stuck"""

# imports
import rclpy
import math as m
from rclpy.node import Node
from geometry_msgs.msg import PoseStamped, PoseWithCovarianceStamped, Twist
from kobuki_ros_interfaces.msg import ButtonEvent
from std_msgs.msg import String
import time, threading

# main class
class RobotLogic(Node):
    
    def __init__(self, name="robot_logic", timerFreq = 1/60.0):
        """ constructor """
        super().__init__(name)  # Create the node

        # Initialize parameters
        self.point0 = [[-0.45803, -2.6858], [-0.37842, 0.92563]]
        self.pointA = [[1.9641, -1.8761], [0.37684,0.9273]]
        self.pointB1 = [[-1.776, -4.393], [0,0]]
        self.pointB2 = [[2.772, -6.364], [0,0]]

        # Initialize subscribers
        self.create_subscription(String, 'ned2', self.robot_full_callback, 10)
        self.create_subscription(Twist, 'multi/cmd_nav', self.robot_vel_callback, 10)
        self.create_subscription(ButtonEvent, '/events/button', self.btn_callback, 10)

        # Initialize a publisher
        self._goal_publisher = self.create_publisher(PoseStamped, 'goal_pose', 10)
        self._initialpose_publisher = self.create_publisher(PoseWithCovarianceStamped, 'initialpose', 10)
        self._backTo0_publisher = self.create_publisher(String, 'pibot', 10)

        # Initialize a clock for the publisher
        # self.create_timer(timerFreq, self.publish_velo)

        # Initialize variables
        self._timerFreq = timerFreq
        self._previousScanTime = None
        self._points = []
        self._firstPointSeen = None
        self._moving = False
        self._challengeId = 1


        # Setup Initial pose to the A point
        initialPoseWithCovariance = self.pointToPoseWithCovarianceStamped(self.point0)
        self._initialpose_publisher.publish(initialPoseWithCovariance)

    # When the map is loaded, move next to the Ned2 robot
    def moveTo0(self):
        print("move back")
        self.moveToPosition(self.point0)

    def moveToB1(self):
        print("move to B1")
        self.moveToPosition(self.pointB1)

    def moveToB2(self):
        print("move to B2")
        self.moveToPosition(self.pointB2)
    
    def moveToA(self):
        print("move to A")
        self.moveToPosition(self.pointA)

    def robot_full_callback(self, msg):

        # Only move if not already moving
        if not self._moving:

            if self._challengeId == 1:

                print('Robot full, go to A')

                # When the robot is full, move to the A point
                self.moveToA()

                # Wait 20s before coming back
                timer = threading.Timer(20, self.moveTo0)
                timer.start()

            else:
                print('Robot full, go to B1, B2, A')

                # When the robot is full, move to the B1 point
                self.moveToB1()

                # Wait before going to B2
                timer = threading.Timer(60, self.moveToB2)
                timer.start()

                # Wait 20s before coming back
                timer3 = threading.Timer(220, self.moveTo0)
                timer3.start()


            self._moving = True
    
    def robot_vel_callback(self, msg):
        if msg == Twist():
            print('Robot stopped')
            self._moving = False

    def btn_callback(self, msg):
        """
        Change challenge
        """
        if(msg.state == msg.PRESSED):
            if self._challengeId == 1:
                self._challengeId = 2 
            else:
                self._challengeId = 1 

            print(f"Challenge ID : {self._challengeId}")
            str = String()
            self._backTo0_publisher.publish(str) # Tell Niryo that we are back in the position


    def moveToPosition(self, point):
        # Create a pose that corresponds to the final destination
        destination = self.pointToPoseStamped(point)

        # Tell robot to move to the position
        self._goal_publisher.publish(destination)


    def pointToPoseStamped(self, point):
        newPose = PoseStamped()
        newPose.pose = self.addPointToPose(newPose.pose, point)

        newPose = self.addHeaders(newPose)

        return newPose

    def pointToPoseWithCovarianceStamped(self, point):
        newPoseWithCovariance = PoseWithCovarianceStamped()
        newPoseWithCovariance.pose.pose = self.addPointToPose(newPoseWithCovariance.pose.pose, point)

        newPoseWithCovariance = self.addHeaders(newPoseWithCovariance)

        return newPoseWithCovariance
    
    def addPointToPose(self,newPose,point):
        newPose.position.x = point[0][0]
        newPose.position.y = point[0][1]

        newPose.orientation.z = point[1][0]
        newPose.orientation.w = point[1][1]

        return newPose

    def addHeaders(self, el):
        el.header.frame_id = "map"
        el.header.stamp = self.get_clock().now().to_msg()

        return el


# Main loop
def main():
    """
    Main loop
    """
    rclpy.init()
    rosNode = RobotLogic()
    rclpy.spin(rosNode)


    rosNode.destroy_node()
    rclpy.shutdown()

if __name__ == "__main__":
    main()